#!/bin/bash

set -e
set -u

cd $(dirname "$0")

pushd web
grunt build
popd

rm -rf dist
git clone --branch gh-pages "git@github.com:oremj/tdeecalc.git" dist

rsync --exclude=".git" \
    --exclude=".git-ignore" \
    -av --delete web/dist/ dist/

cd dist;

echo www.tdeecalc.com > CNAME

git add .
git commit -a -m "$(date)"
git push
